nelmio_api_doc:
  areas:
    default:
      path_patterns: [ ^/api ]
  documentation:
    info:
      title: '%env(APP_NAME)%'
      version: '%env(APP_VERSION)%'
    servers:
      - url: '%env(DEFAULT_URI)%'
        description: API Gateway
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
      schemas:
        ErrorResponse:
          type: object
          properties:
            code:
              type: string
              format: uuid
            error:
              type: string
            violations:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  reason:
                    type: string
                required:
                  - name
                  - reason
          required:
            - code
            - error
