framework:
  rate_limiter:
    limiters:
      email_ip_login:
        policy: token_bucket
        limit: 5
        rate: { interval: '5 minutes' }
        cache_pool: cache.rate_limiter
      ip_login:
        policy: sliding_window
        limit: 50
        interval: '15 minutes'
        cache_pool: cache.rate_limiter
