framework:
  default_locale: !php/const App\Domain\Entity\LocaleCode::EN
  translator:
    default_path: '%kernel.project_dir%/src/Presentation/Resource/Translation'
    fallbacks: [ !php/const App\Domain\Entity\LocaleCode::EN ]
