twig:
  default_path: '%kernel.project_dir%/src/Presentation/Resource/Template'
  paths:
    '%kernel.project_dir%/src/Presentation/Resource/Template/emails': emails
    '%kernel.project_dir%/src/Presentation/Resource/Template/views': views

when@test:
  twig:
    strict_variables: true
