twig:
  default_path: '%kernel.project_dir%/src/Presentation/Resource/Template'
  paths:
    '%kernel.project_dir%/src/Presentation/Resource/Template/email': 'email'

when@test:
  twig:
    strict_variables: true
