Nelmio\ApiDocBundle\Controller\DocumentationController:
  path: /docs/json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

Nelmio\ApiDocBundle\Controller\SwaggerUiController:
  path: /docs
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
