app_swagger_json:
  path: /docs/json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_json }

app_swagger_ui:
  path: /docs
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
