#!/usr/bin/env sh

COMMAND="${1:-application}"
ENVIRONMENT="${APP_ENV:-prod}"

if [ "$ENVIRONMENT" != "prod" ]; then
    /bin/echo "Running development environment."
    /bin/cp $PWD/config/docker/development.conf /usr/local/etc/php/php.ini
fi

if [ "$COMMAND" = "application" ]; then
    /bin/echo "Starting symfony application services."

    if [ "$ENVIRONMENT" != "prod" ]; then
        /sbin/runuser -u www-data -- /usr/bin/composer install --no-interaction
    else
        /sbin/runuser -u www-data -- /usr/bin/composer auto-scripts
    fi

    /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
elif [ "$COMMAND" = "messenger" ]; then
    /bin/echo "Handling messages from async queue."
    /usr/bin/supervisord -c /etc/supervisor/messenger.conf
elif [ "$COMMAND" = "migration" ]; then
    /bin/echo "Upgrading database by migrations."
    /sbin/runuser -u www-data -- /usr/bin/composer auto-migrate
elif [ "$COMMAND" = "quality" ]; then
    /bin/echo "Starting code quality assurance tests."
    /bin/cp $PWD/config/docker/development.conf /usr/local/etc/php/php.ini
    /sbin/runuser -u www-data -- /usr/bin/composer install --no-interaction --no-scripts
    /sbin/runuser -u www-data -- /usr/bin/composer auto-analyze
    /sbin/runuser -u www-data -- /usr/bin/composer auto-quality
fi
