#!/usr/bin/env sh
set -eux

COMMAND="${1:-application}"
ENVIRONMENT="${APP_ENV:-}"

if [ "$ENVIRONMENT" != "prod" ]; then
    /bin/echo "Running development environment."
    /bin/cp "$PWD/config/docker/development.conf" /usr/local/etc/php/php.ini
    /sbin/runuser -u www-data -- /usr/bin/composer install --no-interaction --no-scripts
fi

case "$COMMAND" in
    application)
        /bin/echo "Starting symfony application services."
        /sbin/runuser -u www-data -- /usr/bin/composer auto-scripts
        exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
        ;;
    messenger)
        /bin/echo "Handling messages from async queue."
        exec /usr/bin/supervisord -c /etc/supervisor/messenger.conf
        ;;
    migration)
        /bin/echo "Upgrading database by migrations."
        exec /sbin/runuser -u www-data -- /usr/bin/composer auto-migrate
        ;;
    quality)
        /bin/echo "Starting code quality assurance tests."
        /sbin/runuser -u www-data -- /usr/bin/composer auto-analyze
        exec /sbin/runuser -u www-data -- /usr/bin/composer auto-quality
        ;;
    *)
        /bin/echo "Unknown command: $COMMAND" >&2
        exit 1
        ;;
esac
