services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'
      - '../src/Application/{Event}/'
      - '../src/Domain/{Entity,Exception}/'
      - '../src/Infrastructure/Persistence/Doctrine/{Migration}/'

  App\Domain\Contract\JwtTokenManagerInterface:
    class: App\Infrastructure\Adapter\LcobucciJwtAdapter
    arguments:
      $lifetime: '%env(int:JWT_LIFETIME)%'
      $passphrase: '%env(JWT_PASSPHRASE)%'
      $signingKey: '%env(default::JWT_SIGNING_KEY)%'
      $verificationKey: '%env(default::JWT_VERIFICATION_KEY)%'
